### ISSUE TITLE
Bros pls Can u Fix This

### ISSUE THREAD

**Issue by fidelity2851** [yudax42/vue-upload-drop-images#11]
![Screenshot 2021-06-14 182024](https://user-images.githubusercontent.com/46867012/121933064-7f74eb00-cd3d-11eb-9dd8-298761125a44.png)

The files is returning 2 array. Pls FIX.

**Comment by fidelity2851** [comment]
Pls Its works Fine when u drop the images
but BUG when u select them 1 after the Other
Can u FIX Urgently.

**Comment by yudax42** [comment]
Hello @fidelity2851,
I just checked it works fine, I think there is a problem on your side, can you share the code of the function that handles the event?

**Comment by fidelity2851** [comment]
<UploadImages @change="ImagesSelected" />

ImagesSelected(files) {
      this.Advert.images = files
      console.log(files)
    },


Am using Vue 3

**Comment by yudax42** [comment]
It looks fine, maybe something else caused this problem, please DM me on Twitter `@yudax42` so I can help you debug your code.
Have a great day!

**Comment by fidelity2851** [comment]
Pls inbox is closed on Twitter

**Comment by CyferZ** [comment]
Hi, I know this is closed, but I found the issue, for future reference or if @fidelity2851 still needs help.

I think it's because he is using Vue3 (like I am). I saw this only supports Vue2, but most of the methods and stuff seemed fine for Vue3, so I took a risk and stumbled upon this same error. For some reason whenever you clicked on the Upload Images section, or the Append "button", it FIRST assigned the files to the array, and then completely replaced it afterwards with ALL of the $event argument keys and values. 

I fixed this by changing the $emit method name inside the component from this.$emit("change", this.files) to this.$emit("changed", this.files);

It seems there was a "conflict of interest" in a way, elements fighting over a method name, seeing as you are calling on the onchange event on the input:file inside the component and then naming the emitted method the same thing. @yudax42 I'd suggest giving the emitted method a new name. You could even use the one I "changed" it to ;P ... Until you do, anybody else that wants to use this amazing component will have to physically rename that emitted method themselves inside the (/node_modules/vue-upload-drop-images/dist) folder.

Loved this component, that's why I took the time to see what could make this more friendly to Vue3. 

Keep up the good work @yudax42!

**Comment by yudax42** [comment]
Hello @CyferZ,
First I want to thank you for taking time to look for a solution to that problem and for your kind words! 
I tried to debug the code before and I didn't notice this issue, Your suggestion seems very logical and right. i will  update the code to fix it.
 I really appreciate your help !

**Comment by CyferZ** [comment]
Not a problem! That's what us developers are here for. I'm very glad I was able to help, and hope I'll be able to keep supporting your repo through future Vue updates. ^^

**Comment by fidelity2851** [comment]
Thanks guys everything works fine now
💚💚💚

**Comment by jineshsubedi** [comment]
facing the same problem
