### ISSUE TITLE
bug after clearing all images

### ISSUE THREAD

**Issue by fidelity2851** [yudax42/vue-upload-drop-images#9]
After Clearing all images it automatically submits my form. pls fix

**Comment by petar-bracko** [comment]
That's because the "clear All" button is defined like: <button class="clearButton" @click="reset">. Type should be specified as "button" like: <button **type="button"** class="clearButton" @click="reset"> in your _node_modules_, so it does not automatically submit the form it is used in. Don't forget to rebuild the project after changing that (npm run dev). Hope this helps.

**Comment by fidelity2851** [comment]
Thanks man I Appreciate

**Comment by tisocl** [comment]
Is there any way to fix this without changing anything inside the module?

**Comment by petar-bracko** [comment]
I don't see any other way of doing this. The only thing you can change regarding that button is text inside of it with 'clearAll' prop on component. Components logic is not exposed, therefore you can't change much, other than through props ( https://github.com/yudax42/vue-upload-drop-images#props ).

**Comment by yudax42** [comment]
Hello guys!
sorry, I didn't notice this problem.
i will fix it now, Thank you

**Comment by tisocl** [comment]
Thanks!!

**Comment by fidelity2851** [comment]
Good Works Fine Now
